import type {
  ClientType,
  Difficulty,
  InstrumentConfig,
  InstrumentTrainingProfile,
  ScenarioFamily,
} from '../types'

export const APEX_EQUITY: InstrumentConfig = {
  id: 'apex-equity',
  assetClass: 'single-stock-equity',
  symbol: 'APEX',
  displayName: 'Apex Dynamics',
  baseCurrency: 'SHARES',
  quoteCurrency: 'USD',
  initialPrice: 250,
  pipSize: 0.01,
  priceDecimals: 2,
  defaultSizeM: 5,
  minimumSizeM: 1,
  maximumSizeM: 120,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: 'k shares',
  pnlMultiplier: 1_000,
  commissionMultiplier: 3.5,
  positionLimitScale: 1.35,
  eventSensitivity: {
    inflation: 0.8,
    growth: 0.9,
    policy: 0.75,
    risk: 1.2,
    energy: 0.25,
    company: 1.6,
  },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 1_000,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 1.15,
  spreadScale: 1.25,
  impactCoefficientPips: 1.45,
  impactRecoverySeconds: 18,
  volatilityScale: 1,
  equityProfile: {
    archetype: 'Liquid large-cap',
    sector: 'Technology / industrial growth',
    description: 'Balanced block market: meaningful depth, moderate event risk and enough market impact to reward internalisation and patient hedging.',
    typicalRfqMinM: 5,
    typicalRfqMaxM: 20,
    liquidityLabel: 'High',
    volatilityLabel: 'Moderate',
    impactLabel: 'Moderate',
    scheduledCompanyHeadlines: [
      { headline: 'APEX investor update due', detail: 'Management guidance may change expected earnings and near-term positioning.', factor: 'company' },
      { headline: 'APEX order-book update due', detail: 'A commercial update may change expectations for forward revenue and margins.', factor: 'company' },
    ],
    surpriseCompanyHeadlines: [
      { headline: 'APEX guidance headline crosses', detail: 'An unscheduled company update changes the earnings outlook.', factor: 'company' },
      { headline: 'APEX major customer order hits tape', detail: 'A large commercial announcement changes near-term growth expectations.', factor: 'company' },
    ],
  },
}

export const MEGA_EQUITY: InstrumentConfig = {
  id: 'mega-equity',
  assetClass: 'single-stock-equity',
  symbol: 'MEGA',
  displayName: 'Mega Systems',
  baseCurrency: 'SHARES',
  quoteCurrency: 'USD',
  initialPrice: 418.24,
  pipSize: 0.01,
  priceDecimals: 2,
  defaultSizeM: 7,
  minimumSizeM: 1,
  maximumSizeM: 160,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: 'k shares',
  pnlMultiplier: 1_000,
  commissionMultiplier: 3.0,
  positionLimitScale: 1.6,
  eventSensitivity: {
    inflation: 0.75,
    growth: 0.82,
    policy: 0.7,
    risk: 1.0,
    energy: 0.12,
    company: 1.35,
  },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 1_000,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 1.62,
  spreadScale: 0.86,
  impactCoefficientPips: 0.82,
  impactRecoverySeconds: 11,
  volatilityScale: 0.78,
  equityProfile: {
    archetype: 'Mega-cap / very liquid',
    sector: 'Large-cap technology',
    description: 'Deep book and fast replenishment. Bigger blocks can be priced competitively, but over-hedging still destroys edge through repeated spread crossing.',
    typicalRfqMinM: 7,
    typicalRfqMaxM: 25,
    liquidityLabel: 'Very high',
    volatilityLabel: 'Moderate',
    impactLabel: 'Low',
    scheduledCompanyHeadlines: [
      { headline: 'MEGA product and AI infrastructure update due', detail: 'Management commentary may alter expectations for capital spending and growth.', factor: 'company' },
      { headline: 'MEGA quarterly trading update due', detail: 'Revenue and margin commentary may reprice the stock despite deep liquidity.', factor: 'company' },
    ],
    surpriseCompanyHeadlines: [
      { headline: 'MEGA cloud demand headline crosses', detail: 'A demand update shifts expectations for forward growth.', factor: 'company' },
      { headline: 'MEGA announces accelerated buyback', detail: 'Unexpected corporate flow changes short-term demand and dealer positioning.', factor: 'company' },
    ],
  },
}

export const NOVA_EQUITY: InstrumentConfig = {
  id: 'nova-equity',
  assetClass: 'single-stock-equity',
  symbol: 'NOVA',
  displayName: 'Nova Learning',
  baseCurrency: 'SHARES',
  quoteCurrency: 'USD',
  initialPrice: 96.71,
  pipSize: 0.01,
  priceDecimals: 2,
  defaultSizeM: 5,
  minimumSizeM: 1,
  maximumSizeM: 90,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: 'k shares',
  pnlMultiplier: 1_000,
  commissionMultiplier: 4.4,
  positionLimitScale: 1.05,
  eventSensitivity: {
    inflation: 0.92,
    growth: 1.15,
    policy: 0.95,
    risk: 1.5,
    energy: 0.08,
    company: 2.0,
  },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 1_000,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 0.72,
  spreadScale: 1.55,
  impactCoefficientPips: 2.05,
  impactRecoverySeconds: 25,
  volatilityScale: 1.58,
  equityProfile: {
    archetype: 'High-beta growth',
    sector: 'Consumer internet / software',
    description: 'Thinner depth and much larger event sensitivity. Client blocks create visible price impact, so clip sizing and toxic-flow judgement matter more.',
    typicalRfqMinM: 4,
    typicalRfqMaxM: 16,
    liquidityLabel: 'Moderate',
    volatilityLabel: 'Very high',
    impactLabel: 'High',
    scheduledCompanyHeadlines: [
      { headline: 'NOVA subscriber-growth update due', detail: 'User growth and monetisation data may materially change the earnings path.', factor: 'company' },
      { headline: 'NOVA product metrics release due', detail: 'Engagement data may change assumptions for growth and operating leverage.', factor: 'company' },
    ],
    surpriseCompanyHeadlines: [
      { headline: 'NOVA engagement data leaks onto tape', detail: 'Unexpected operating data changes growth expectations in a relatively thin market.', factor: 'company' },
      { headline: 'NOVA secondary placement rumour crosses', detail: 'Potential new supply temporarily worsens liquidity and raises execution risk.', factor: 'risk' },
    ],
  },
}

export const HELI_EQUITY: InstrumentConfig = {
  id: 'heli-equity',
  assetClass: 'single-stock-equity',
  symbol: 'HELI',
  displayName: 'Helix Pharma',
  baseCurrency: 'SHARES',
  quoteCurrency: 'USD',
  initialPrice: 143.08,
  pipSize: 0.01,
  priceDecimals: 2,
  defaultSizeM: 6,
  minimumSizeM: 1,
  maximumSizeM: 110,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: 'k shares',
  pnlMultiplier: 1_000,
  commissionMultiplier: 3.8,
  positionLimitScale: 1.25,
  eventSensitivity: {
    inflation: 0.42,
    growth: 0.5,
    policy: 0.35,
    risk: 0.72,
    energy: 0.05,
    company: 1.85,
  },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 1_000,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 1.05,
  spreadScale: 1.04,
  impactCoefficientPips: 1.18,
  impactRecoverySeconds: 16,
  volatilityScale: 0.86,
  equityProfile: {
    archetype: 'Defensive large-cap',
    sector: 'Healthcare / pharmaceuticals',
    description: 'Normally steadier macro beta, but company-specific trial and regulatory headlines can abruptly dominate an otherwise orderly book.',
    typicalRfqMinM: 5,
    typicalRfqMaxM: 20,
    liquidityLabel: 'High',
    volatilityLabel: 'Low',
    impactLabel: 'Moderate',
    scheduledCompanyHeadlines: [
      { headline: 'HELI clinical update due', detail: 'Trial data may dominate normal defensive-sector trading behaviour.', factor: 'company' },
      { headline: 'HELI regulatory decision due', detail: 'A scheduled regulatory outcome may change expected product cash flows.', factor: 'company' },
    ],
    surpriseCompanyHeadlines: [
      { headline: 'HELI trial headline crosses', detail: 'Unexpected clinical news abruptly reprices company-specific risk.', factor: 'company' },
      { headline: 'HELI acquisition report hits tape', detail: 'An unscheduled strategic report changes valuation and near-term flow.', factor: 'company' },
    ],
  },
}

export const LUMA_EQUITY: InstrumentConfig = {
  id: 'luma-equity',
  assetClass: 'single-stock-equity',
  symbol: 'LUMA',
  displayName: 'Luma Robotics',
  baseCurrency: 'SHARES',
  quoteCurrency: 'USD',
  initialPrice: 184.32,
  pipSize: 0.01,
  priceDecimals: 2,
  defaultSizeM: 5,
  minimumSizeM: 1,
  maximumSizeM: 70,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: 'k shares',
  pnlMultiplier: 1_000,
  commissionMultiplier: 4.8,
  positionLimitScale: 0.86,
  eventSensitivity: {
    inflation: 0.82,
    growth: 1.05,
    policy: 0.78,
    risk: 1.45,
    energy: 0.16,
    company: 2.05,
  },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 1_000,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 0.46,
  spreadScale: 2.35,
  impactCoefficientPips: 3.25,
  impactRecoverySeconds: 38,
  volatilityScale: 1.34,
  microstructure: {
    cancellationSensitivity: 1.35,
    hiddenLiquidityShare: 0.11,
    spreadElasticity: 1.45,
    imbalanceSensitivity: 1.28,
    leakageSensitivity: 1.35,
  },
  equityProfile: {
    archetype: 'Less-liquid mid-cap',
    sector: 'Industrial automation / robotics',
    description: 'Shallower depth, wider normal spreads and slower replenishment. Large client blocks make internalisation and staged execution materially more valuable.',
    typicalRfqMinM: 5,
    typicalRfqMaxM: 15,
    liquidityLabel: 'Low',
    volatilityLabel: 'High',
    impactLabel: 'High',
    scheduledCompanyHeadlines: [
      { headline: 'LUMA trading update due', detail: 'Order intake and margin guidance can materially reprice a thinner mid-cap book.', factor: 'company' },
      { headline: 'LUMA investor day due', detail: 'Capacity and demand commentary may change medium-term growth expectations.', factor: 'company' },
    ],
    surpriseCompanyHeadlines: [
      { headline: 'LUMA contract headline crosses', detail: 'A large customer award creates one-sided flow in a relatively shallow market.', factor: 'company' },
      { headline: 'LUMA placement rumour hits tape', detail: 'Potential new supply causes market makers to pull bids and widen prices.', factor: 'risk' },
    ],
  },
}

export const ORBX_EQUITY: InstrumentConfig = {
  id: 'orbx-equity',
  assetClass: 'single-stock-equity',
  symbol: 'ORBX',
  displayName: 'Orbex Therapeutics',
  baseCurrency: 'SHARES',
  quoteCurrency: 'USD',
  initialPrice: 62.48,
  pipSize: 0.01,
  priceDecimals: 2,
  defaultSizeM: 4,
  minimumSizeM: 1,
  maximumSizeM: 45,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: 'k shares',
  pnlMultiplier: 1_000,
  commissionMultiplier: 6.0,
  positionLimitScale: 0.66,
  eventSensitivity: {
    inflation: 0.55,
    growth: 0.65,
    policy: 0.48,
    risk: 1.85,
    energy: 0.05,
    company: 3.0,
  },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 1_000,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 0.27,
  spreadScale: 3.8,
  impactCoefficientPips: 5.6,
  impactRecoverySeconds: 58,
  volatilityScale: 2.15,
  microstructure: {
    cancellationSensitivity: 2.05,
    hiddenLiquidityShare: 0.06,
    spreadElasticity: 2.1,
    imbalanceSensitivity: 1.75,
    leakageSensitivity: 2.0,
  },
  equityProfile: {
    archetype: 'Event-driven small/mid-cap',
    sector: 'Biotechnology',
    description: 'Very shallow and unstable liquidity. Large aggressive trades can move the market, trigger cancellations and leave a visible footprint for an extended period.',
    typicalRfqMinM: 3,
    typicalRfqMaxM: 12,
    liquidityLabel: 'Low',
    volatilityLabel: 'Very high',
    impactLabel: 'Very high',
    scheduledCompanyHeadlines: [
      { headline: 'ORBX clinical data due', detail: 'A binary clinical update can dominate normal price formation and liquidity.', factor: 'company' },
      { headline: 'ORBX regulatory meeting due', detail: 'Regulatory commentary may create abrupt one-sided positioning.', factor: 'company' },
    ],
    surpriseCompanyHeadlines: [
      { headline: 'ORBX trial rumour crosses', detail: 'Unverified clinical chatter causes displayed liquidity to vanish and spreads to jump.', factor: 'company' },
      { headline: 'ORBX financing headline hits tape', detail: 'Potential capital raising creates rapid cancellations on the bid side.', factor: 'risk' },
    ],
  },
}

export const EUR_USD: InstrumentConfig = {
  id: 'eur-usd',
  assetClass: 'fx',
  symbol: 'EUR/USD',
  displayName: 'Euro / US Dollar',
  baseCurrency: 'EUR',
  quoteCurrency: 'USD',
  initialPrice: 1.085,
  pipSize: 0.0001,
  priceDecimals: 5,
  defaultSizeM: 5,
  minimumSizeM: 0.5,
  maximumSizeM: 100,
  sizeStepM: 0.5,
  sizePrefix: '€',
  sizeSuffix: 'm',
  pnlMultiplier: 1_000_000,
  commissionMultiplier: 1,
  positionLimitScale: 1,
  eventSensitivity: {
    inflation: 1, growth: 0.85, policy: 1.1, risk: 0.8, energy: 0.35, company: 0.1,
  },
  marketStructure: 'dealer-otc',
  unitsPerSize: 1_000_000,
  orderBookLevels: 3,
  displayedDepthLevels: 3,
  depthScale: 1,
  spreadScale: 1,
  impactCoefficientPips: 0.45,
  impactRecoverySeconds: 10,
  volatilityScale: 1,
}

export const BUND_FUTURE: InstrumentConfig = {
  id: 'bund',
  assetClass: 'rates',
  symbol: 'FGBL',
  displayName: 'Euro-Bund Future',
  baseCurrency: 'EUR',
  quoteCurrency: 'EUR',
  initialPrice: 132.5,
  pipSize: 0.01,
  priceDecimals: 2,
  defaultSizeM: 60,
  minimumSizeM: 1,
  maximumSizeM: 500,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: ' contracts',
  pnlMultiplier: 1_000,
  commissionMultiplier: 0.18,
  positionLimitScale: 4.2,
  eventSensitivity: { inflation: 1.45, growth: 1.05, policy: 1.6, risk: 0.95, energy: 0.5, company: 0.05 },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 1_000,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 2.1,
  spreadScale: 0.82,
  impactCoefficientPips: 0.62,
  impactRecoverySeconds: 9,
  volatilityScale: 0.8,
  trainingProfile: {
    archetype: 'Liquid European rates future',
    marketFocus: 'Duration, inflation and ECB repricing',
    description: 'Deep central order book with tight ticks in normal conditions. Macro releases can move the contract sharply, while large clips still create footprint when liquidity thins.',
    typicalRfqMinM: 25,
    typicalRfqMaxM: 120,
    liquidityLabel: 'Very high',
    volatilityLabel: 'Moderate',
    impactLabel: 'Low',
    scheduledHeadlines: [
      { headline: 'ECB rate decision due', detail: 'The policy decision and guidance may reprice the euro rates curve and Bund duration.', factor: 'policy' },
      { headline: 'Euro-area inflation data due', detail: 'Inflation data may change expectations for the pace and depth of ECB easing.', factor: 'inflation' },
      { headline: 'German CPI flash due', detail: 'German inflation can move front-end and long-end euro rates expectations.', factor: 'inflation' },
      { headline: 'Euro-area PMI data due', detail: 'Growth momentum can alter the expected path of policy and term premium.', factor: 'growth' },
    ],
    surpriseHeadlines: [
      { headline: 'ECB source report crosses', detail: 'An unscheduled policy report changes the perceived path of rates.', factor: 'policy' },
      { headline: 'Large Bund block sweeps the book', detail: 'Aggressive duration flow consumes depth and briefly shifts price discovery.', factor: 'risk' },
      { headline: 'European risk-off move accelerates', detail: 'A flight-to-quality impulse changes Bund demand and liquidity.', factor: 'risk' },
    ],
  },
}

export const BRENT_FUTURE: InstrumentConfig = {
  id: 'brent',
  assetClass: 'commodities',
  symbol: 'BRN',
  displayName: 'ICE Brent Crude Future',
  baseCurrency: 'BBL',
  quoteCurrency: 'USD',
  initialPrice: 79.25,
  pipSize: 0.01,
  priceDecimals: 2,
  defaultSizeM: 30,
  minimumSizeM: 1,
  maximumSizeM: 250,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: ' contracts',
  pnlMultiplier: 1_000,
  commissionMultiplier: 0.18,
  positionLimitScale: 2.2,
  eventSensitivity: { inflation: 0.28, growth: 0.9, policy: 0.2, risk: 0.8, energy: 1.8, company: 0.05 },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 1_000,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 0.9,
  spreadScale: 1.15,
  impactCoefficientPips: 1.45,
  impactRecoverySeconds: 19,
  volatilityScale: 1.25,
  trainingProfile: {
    archetype: 'Global crude-oil future',
    marketFocus: 'Inventory, OPEC+, geopolitics and growth',
    description: 'Good liquidity in normal conditions but materially larger event jumps and impact than the rates future. Working residuals matters when headlines thin the book.',
    typicalRfqMinM: 10,
    typicalRfqMaxM: 70,
    liquidityLabel: 'High',
    volatilityLabel: 'High',
    impactLabel: 'Moderate',
    scheduledHeadlines: [
      { headline: 'US crude inventory data due', detail: 'Inventory changes can alter the near-term physical balance and prompt fast futures repricing.', factor: 'energy' },
      { headline: 'OPEC+ meeting headlines due', detail: 'Production guidance can materially change expected crude supply.', factor: 'energy' },
      { headline: 'Global growth data due', detail: 'Demand expectations can shift the crude curve and outright price.', factor: 'growth' },
      { headline: 'Saudi official selling prices due', detail: 'Pricing signals may alter expectations for regional physical tightness.', factor: 'energy' },
    ],
    surpriseHeadlines: [
      { headline: 'Pipeline disruption headline crosses', detail: 'Unexpected supply disruption tightens the prompt market and raises volatility.', factor: 'energy' },
      { headline: 'OPEC+ delegate comment hits tape', detail: 'An unscheduled production comment changes supply expectations.', factor: 'energy' },
      { headline: 'Geopolitical risk premium jumps', detail: 'Shipping or regional risk abruptly reduces liquidity and lifts short-term volatility.', factor: 'risk' },
    ],
  },
}

export const SP500_FUTURE: InstrumentConfig = {
  id: 'sp500',
  assetClass: 'equity-index',
  symbol: 'ES',
  displayName: 'E-mini S&P 500 Future',
  baseCurrency: 'INDEX',
  quoteCurrency: 'USD',
  initialPrice: 5400,
  pipSize: 0.25,
  priceDecimals: 2,
  defaultSizeM: 60,
  minimumSizeM: 1,
  maximumSizeM: 500,
  sizeStepM: 1,
  sizePrefix: '',
  sizeSuffix: ' contracts',
  pnlMultiplier: 50,
  commissionMultiplier: 0.16,
  positionLimitScale: 3.4,
  eventSensitivity: { inflation: 1.0, growth: 1.05, policy: 1.1, risk: 1.55, energy: 0.4, company: 0.3 },
  marketStructure: 'central-limit-order-book',
  unitsPerSize: 50,
  orderBookLevels: 8,
  displayedDepthLevels: 8,
  depthScale: 2.25,
  spreadScale: 0.78,
  impactCoefficientPips: 0.55,
  impactRecoverySeconds: 8,
  volatilityScale: 0.95,
  trainingProfile: {
    archetype: 'Highly liquid US equity-index future',
    marketFocus: 'Macro data, risk sentiment and index flow',
    description: 'Very deep book and fast replenishment in normal conditions, but CPI, payrolls and FOMC events can transform the market within seconds.',
    typicalRfqMinM: 20,
    typicalRfqMaxM: 120,
    liquidityLabel: 'Very high',
    volatilityLabel: 'High',
    impactLabel: 'Low',
    scheduledHeadlines: [
      { headline: 'US CPI due', detail: 'Inflation can reprice both the expected policy path and equity valuation multiples.', factor: 'inflation' },
      { headline: 'US payrolls due', detail: 'Labour data changes growth, rates and risk sentiment simultaneously.', factor: 'growth' },
      { headline: 'Federal Reserve decision due', detail: 'Policy guidance can rapidly change index futures, rates and volatility.', factor: 'policy' },
      { headline: 'US retail sales due', detail: 'Consumer demand can alter the growth and earnings outlook.', factor: 'growth' },
    ],
    surpriseHeadlines: [
      { headline: 'Index program flow accelerates', detail: 'Large systematic flow briefly consumes depth and pushes the futures market.', factor: 'risk' },
      { headline: 'Mega-cap earnings headline crosses', detail: 'A major index constituent changes broad equity sentiment outside the scheduled calendar.', factor: 'company' },
      { headline: 'Volatility spike hits risk assets', detail: 'A sudden risk-off move changes both execution cost and client urgency.', factor: 'risk' },
    ],
  },
}

export const EQUITY_INSTRUMENTS = [APEX_EQUITY, MEGA_EQUITY, NOVA_EQUITY, HELI_EQUITY, LUMA_EQUITY, ORBX_EQUITY] as const

export const MACRO_FUTURES = [BUND_FUTURE, BRENT_FUTURE, SP500_FUTURE] as const

export function getInstrumentTrainingProfile(instrument: InstrumentConfig): InstrumentTrainingProfile | undefined {
  if (instrument.trainingProfile) return instrument.trainingProfile
  if (!instrument.equityProfile) return undefined
  return {
    archetype: instrument.equityProfile.archetype,
    marketFocus: instrument.equityProfile.sector,
    description: instrument.equityProfile.description,
    typicalRfqMinM: instrument.equityProfile.typicalRfqMinM,
    typicalRfqMaxM: instrument.equityProfile.typicalRfqMaxM,
    liquidityLabel: instrument.equityProfile.liquidityLabel,
    volatilityLabel: instrument.equityProfile.volatilityLabel,
    impactLabel: instrument.equityProfile.impactLabel,
    scheduledHeadlines: instrument.equityProfile.scheduledCompanyHeadlines,
    surpriseHeadlines: instrument.equityProfile.surpriseCompanyHeadlines,
  }
}

export const INSTRUMENTS = {
  'apex-equity': APEX_EQUITY,
  'mega-equity': MEGA_EQUITY,
  'nova-equity': NOVA_EQUITY,
  'heli-equity': HELI_EQUITY,
  'luma-equity': LUMA_EQUITY,
  'orbx-equity': ORBX_EQUITY,
  'eur-usd': EUR_USD,
  bund: BUND_FUTURE,
  brent: BRENT_FUTURE,
  sp500: SP500_FUTURE,
} as const

export function getInstrument(id: keyof typeof INSTRUMENTS): InstrumentConfig {
  return INSTRUMENTS[id]
}

export interface ScenarioProfile {
  label: string
  description: string
  volatilityPipsPerSqrtSecond: number
  spreadPips: number
  liquidity: number
  driftPipsPerSecond: number
  meanReversion: number
  flowBias: number
  rfqIntensity: number
  toxicityMultiplier: number
  softLimitM: number
  hardLimitM: number
}

export const SCENARIO_PROFILES: Record<Exclude<ScenarioFamily, 'random'>, ScenarioProfile> = {
  balanced: {
    label: 'Balanced Flow',
    description: 'Moderate volatility, two-way client flow and normal market depth.',
    volatilityPipsPerSqrtSecond: 0.22,
    spreadPips: 0.8,
    liquidity: 0.78,
    driftPipsPerSecond: 0,
    meanReversion: 0.004,
    flowBias: 0,
    rfqIntensity: 1,
    toxicityMultiplier: 1,
    softLimitM: 35,
    hardLimitM: 60,
  },
  'one-way': {
    label: 'One-Way Flow',
    description: 'Persistent directional client demand puts inventory management under pressure.',
    volatilityPipsPerSqrtSecond: 0.27,
    spreadPips: 0.9,
    liquidity: 0.69,
    driftPipsPerSecond: 0.018,
    meanReversion: 0.002,
    flowBias: 0.62,
    rfqIntensity: 1.15,
    toxicityMultiplier: 1.05,
    softLimitM: 30,
    hardLimitM: 55,
  },
  'fast-market': {
    label: 'Fast Market',
    description: 'Rapid price changes make stale quotes and delayed hedging expensive.',
    volatilityPipsPerSqrtSecond: 0.5,
    spreadPips: 1.1,
    liquidity: 0.6,
    driftPipsPerSecond: 0.01,
    meanReversion: 0.001,
    flowBias: 0.1,
    rfqIntensity: 1.2,
    toxicityMultiplier: 1.25,
    softLimitM: 28,
    hardLimitM: 50,
  },
  illiquid: {
    label: 'Illiquid Market',
    description: 'Wide spreads, thin depth and costly hedging punish oversized positions.',
    volatilityPipsPerSqrtSecond: 0.34,
    spreadPips: 2.1,
    liquidity: 0.32,
    driftPipsPerSecond: 0.005,
    meanReversion: 0.003,
    flowBias: 0.15,
    rfqIntensity: 0.75,
    toxicityMultiplier: 1.15,
    softLimitM: 24,
    hardLimitM: 42,
  },
  'news-shock': {
    label: 'News Shock',
    description: 'A scheduled macro release changes volatility, liquidity and direction mid-session.',
    volatilityPipsPerSqrtSecond: 0.26,
    spreadPips: 0.9,
    liquidity: 0.72,
    driftPipsPerSecond: 0,
    meanReversion: 0.003,
    flowBias: 0.05,
    rfqIntensity: 1,
    toxicityMultiplier: 1.15,
    softLimitM: 30,
    hardLimitM: 52,
  },
  'toxic-flow': {
    label: 'Toxic Flow',
    description: 'Informed clients selectively trade when your quote is stale or mispriced.',
    volatilityPipsPerSqrtSecond: 0.31,
    spreadPips: 0.9,
    liquidity: 0.63,
    driftPipsPerSecond: 0.005,
    meanReversion: 0.002,
    flowBias: 0.05,
    rfqIntensity: 1.05,
    toxicityMultiplier: 1.65,
    softLimitM: 28,
    hardLimitM: 48,
  },
}

export interface DifficultyProfile {
  label: string
  rfqTimeMin: number
  rfqTimeMax: number
  showClientType: 'full' | 'partial' | 'hidden'
  showRegimeGuidance: boolean
  marketSpeedMultiplier: number
  toxicityMultiplier: number
  sizeMultiplier: number
  eventWarningSeconds: number
}

export const DIFFICULTY_PROFILES: Record<Difficulty, DifficultyProfile> = {
  learning: {
    label: 'Learning',
    rfqTimeMin: 20,
    rfqTimeMax: 25,
    showClientType: 'full',
    showRegimeGuidance: true,
    marketSpeedMultiplier: 0.75,
    toxicityMultiplier: 0.75,
    sizeMultiplier: 0.8,
    eventWarningSeconds: 90,
  },
  standard: {
    label: 'Standard',
    rfqTimeMin: 14,
    rfqTimeMax: 18,
    showClientType: 'partial',
    showRegimeGuidance: false,
    marketSpeedMultiplier: 1,
    toxicityMultiplier: 1,
    sizeMultiplier: 1,
    eventWarningSeconds: 60,
  },
  advanced: {
    label: 'Advanced',
    rfqTimeMin: 9,
    rfqTimeMax: 13,
    showClientType: 'hidden',
    showRegimeGuidance: false,
    marketSpeedMultiplier: 1.18,
    toxicityMultiplier: 1.2,
    sizeMultiplier: 1.18,
    eventWarningSeconds: 30,
  },
  assessment: {
    label: 'Assessment',
    rfqTimeMin: 6,
    rfqTimeMax: 10,
    showClientType: 'hidden',
    showRegimeGuidance: false,
    marketSpeedMultiplier: 1.35,
    toxicityMultiplier: 1.35,
    sizeMultiplier: 1.3,
    eventWarningSeconds: 20,
  },
}

export const CLIENT_TYPE_LABELS: Record<ClientType, string> = {
  corporate: 'Corporate Hedger',
  'asset-manager': 'Asset Manager',
  'hedge-fund': 'Hedge Fund',
  'fast-money': 'Fast Money',
  'retail-aggregator': 'Retail Aggregator',
}

export const CLIENT_NAMES: Record<ClientType, readonly string[]> = {
  corporate: ['Asteron Industries', 'Meridian Air', 'Northstar Energy', 'Valegro Motors'],
  'asset-manager': ['Alderstone AM', 'Helix Capital', 'Wrenfield Partners', 'Marlowe Investments'],
  'hedge-fund': ['Crescent Macro', 'Orion Ridge', 'Redwood Alpha', 'Kepler Strategies'],
  'fast-money': ['Vector Trading', 'Argent Flow', 'Pulse Markets', 'Kinetic Capital'],
  'retail-aggregator': ['NexaFX', 'Atlas Direct', 'Bluefin Retail', 'Cobalt Markets'],
}

export const EQUITY_CLIENT_NAMES: Record<ClientType, readonly string[]> = {
  corporate: ['Apex Buyback Desk', 'Northstar Treasury', 'Valegro Strategic Holdings', 'Meridian Employee Trust'],
  'asset-manager': ['Alderstone Equity', 'Helix Long Only', 'Wrenfield Pension Fund', 'Marlowe Growth Fund'],
  'hedge-fund': ['Redwood Alpha', 'Orion Ridge', 'Kepler Event Driven', 'Crescent Equity'],
  'fast-money': ['Vector Trading', 'Pulse Markets', 'Kinetic Capital', 'Argent Flow'],
  'retail-aggregator': ['Atlas Direct', 'Bluefin Retail', 'Nexa Securities', 'Cobalt Markets'],
}

export const EQUITY_CLIENT_TYPE_LABELS: Record<ClientType, string> = {
  corporate: 'Corporate / Buyback',
  'asset-manager': 'Asset Manager',
  'hedge-fund': 'Hedge Fund',
  'fast-money': 'Fast Money',
  'retail-aggregator': 'Retail Aggregator',
}

export const FUTURES_CLIENT_NAMES: Record<ClientType, readonly string[]> = {
  corporate: ['Northstar Treasury', 'Meridian Hedging Desk', 'Valegro Pension Scheme', 'Asteron Risk Desk'],
  'asset-manager': ['Alderstone Macro', 'Helix Fixed Income', 'Wrenfield Multi-Asset', 'Marlowe Global Markets'],
  'hedge-fund': ['Crescent Macro', 'Orion Ridge', 'Redwood Alpha', 'Kepler Global'],
  'fast-money': ['Vector Trading', 'Argent Flow', 'Pulse Markets', 'Kinetic Capital'],
  'retail-aggregator': ['Atlas Futures', 'Bluefin Direct', 'Nexa Markets', 'Cobalt Execution'],
}

export const FUTURES_CLIENT_TYPE_LABELS: Record<ClientType, string> = {
  corporate: 'Hedger / Treasury',
  'asset-manager': 'Real Money',
  'hedge-fund': 'Hedge Fund',
  'fast-money': 'Fast Money',
  'retail-aggregator': 'Aggregator',
}

export function scenarioLabel(scenario: ScenarioFamily): string {
  if (scenario === 'random') return 'Unknown Market'
  return SCENARIO_PROFILES[scenario].label
}
