import { useMemo, useState } from 'react'
import type { FundMandate } from '../engine/fund-types'

interface Props { mandate: FundMandate; onExit: () => void; onStartPractice: () => void }

type Challenge = { question: string; options?: string[]; correct?: number; input?: 'text'; placeholder?: string; success: string }
type Step = { title: string; copy: string; demo: string[]; challenge: Challenge }

const longShortSteps: Step[] = [
  { title: 'Build alpha, not just beta', copy: 'A long/short fund can make money simply by being net long in a rally. DealerSim therefore separates broad beta P&L from residual alpha.', demo: ['Long MEGA +10% (β 1.18)', 'Short NOVA −7% (β 1.55)', 'Net beta still positive'], challenge: { question: 'If the book still has positive market beta, which trade most directly neutralises it?', options: ['Buy ES', 'Short ES', 'Add more MEGA'], correct: 1, success: 'Correct. A short ES hedge removes broad market beta without closing the single-name views.' } },
  { title: 'Shorts require borrow', copy: 'Single-name shorts need securities borrow. Hard-to-borrow names can have expensive rates, partial capacity or no locate at all.', demo: ['ORBX target −5%', 'Borrow 13.5%+ annualised', 'Capacity is uncertain'], challenge: { question: 'What must happen before establishing the ORBX short?', options: ['Request a locate', 'Buy ES', 'Wait for earnings'], correct: 0, success: 'Correct. You need sufficient borrow capacity before the short can be executed.' } },
  { title: 'Manage gross and net', copy: 'Gross is total absolute exposure; net is directional exposure. They answer different risk questions.', demo: ['Long +10%', 'Short −7%', 'ES hedge −4%'], challenge: { question: 'What are gross and net exposure for this example?', options: ['Gross 21%, net −1%', 'Gross 13%, net +7%', 'Gross 17%, net −4%'], correct: 0, success: 'Correct. Gross = 10 + 7 + 4 = 21%; net = 10 − 7 − 4 = −1%.' } },
  { title: 'Choose the execution route', copy: 'Execution should depend on block size and liquidity. A less-liquid $8m LUMA order should not automatically be crossed in one shot.', demo: ['$8m LUMA block', 'Direct market impact: high', 'Dealers may have axes / inventory'], challenge: { question: 'Which route is the best first price-discovery step for a large illiquid block?', options: ['RFQ several dealers', 'Always cross immediately', 'Ignore the trade'], correct: 0, success: 'Correct. Dealer RFQs can reveal inventory and block liquidity before you decide whether to cross or work the residual.' } },
  { title: 'Hedge beta deliberately', copy: 'A beta hedge can isolate stock-selection risk, but it can also remove macro exposure you intentionally wanted.', demo: ['Single-name beta +0.34', 'Target beta ≈ 0', 'Use ES selectively'], challenge: { question: 'The book has +0.34 beta and you want to isolate alpha. What direction should the ES hedge be?', options: ['Long ES', 'Short ES', 'No hedge can change beta'], correct: 1, success: 'Correct. Short ES reduces positive beta. The live terminal calculates the approximate target for you.' } },
  { title: 'Write an invalidation condition', copy: 'A useful thesis states what evidence would make you reassess. It should not simply say “price goes down.”', demo: ['Thesis: earnings estimates too low', 'Catalyst: results + guidance', 'Need evidence-based invalidation'], challenge: { question: 'Write one condition that would invalidate the thesis.', input: 'text', placeholder: 'e.g. Guidance is cut and forward estimates fall below my base case', success: 'Good. In the live session, record invalidation only for positions you genuinely want reviewed.' } },
]

const longOnlySteps: Step[] = [
  { title: 'Think relative to a benchmark', copy: 'The long-only mandate is scored against a synthetic benchmark. An underweight is an active view even when you still own the stock.', demo: ['Benchmark MEGA 25%', 'Your MEGA 15%', 'Active weight −10%'], challenge: { question: 'If MEGA rallies sharply while you own 15% versus a 25% benchmark weight, what happens?', options: ['You outperform because you owned it', 'You underperform relative to benchmark', 'No benchmark effect'], correct: 1, success: 'Correct. You made money absolutely but still lagged the benchmark because you were underweight.' } },
  { title: 'Size active bets', copy: 'A portfolio can look diversified by ticker while still being concentrated in one factor or one oversized active position.', demo: ['HELI +8% active', 'NOVA +7% active', 'Growth factor already elevated'], challenge: { question: 'What should you check before adding another high-growth overweight?', options: ['Only the stock price', 'Portfolio factor and concentration risk', 'Whether the ticker is popular'], correct: 1, success: 'Correct. Active weights should be judged in portfolio context, not one stock at a time.' } },
  { title: 'Execution still matters', copy: 'Asset managers also need block liquidity. Arrival price and implementation shortfall matter even when the investment thesis is correct.', demo: ['$6m LUMA buy', 'Thin liquidity', 'Dealer specialist shows an axe'], challenge: { question: 'A specialist dealer offers a full block 4bp better than direct execution. What is the sensible action?', options: ['Evaluate / use the dealer quote', 'Cross the market regardless', 'Cancel the investment thesis'], correct: 0, success: 'Correct. Execution is part of portfolio implementation; better block liquidity preserves alpha.' } },
  { title: 'Reassess around catalysts', copy: 'Earnings, guidance and macro news change the opportunity set continuously. A long-only portfolio should rebalance when information changes, not on a fixed schedule.', demo: ['MEGA earnings beat', 'Rates rise sharply', 'Growth multiple compresses'], challenge: { question: 'The earnings thesis is right but the stock falls because rates reprice. What should you do?', options: ['Automatically double the position', 'Reassess both company thesis and factor risk', 'Ignore macro because this is equity AM'], correct: 1, success: 'Correct. A correct company view can still be overwhelmed by factor risk; the portfolio decision has to reflect both.' } },
]

export function FundTutorial({ mandate, onExit, onStartPractice }: Props) {
  const steps = mandate === 'long-short' ? longShortSteps : longOnlySteps
  const [index, setIndex] = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const [text, setText] = useState('')
  const [solved, setSolved] = useState(false)
  const step = steps[index]
  const canSolveText = step.challenge.input === 'text' && text.trim().length >= 10
  const status = useMemo(() => solved ? step.challenge.success : '', [solved, step.challenge.success])
  const answerOption = (optionIndex: number) => { setSelected(optionIndex); setSolved(optionIndex === step.challenge.correct) }
  const next = () => { if (index < steps.length - 1) { setIndex(index + 1); setSelected(null); setText(''); setSolved(false) } }
  return <main className="fund-tutorial-shell"><header><div><p className="eyebrow">BUY-SIDE INTERACTIVE TUTORIAL</p><h1>{mandate === 'long-short' ? 'Long / Short Equity Hedge Fund' : 'Long-Only Asset Management'}</h1></div><button className="button button-ghost" onClick={onExit}>Exit tutorial</button></header><div className="fund-tutorial-progress">{steps.map((_, item) => <i key={item} className={item <= index ? 'active' : ''} />)}</div><section><div className="fund-tutorial-demo"><span>Live concept</span>{step.demo.map((item) => <strong key={item}>{item}</strong>)}<p>The exercise on the right must be completed before you advance.</p></div><article><p className="eyebrow">STEP {index + 1} / {steps.length}</p><h2>{step.title}</h2><p>{step.copy}</p><div className="tutorial-challenge"><strong>{step.challenge.question}</strong>{step.challenge.options && <div className="tutorial-option-grid">{step.challenge.options.map((option, optionIndex) => <button key={option} className={selected === optionIndex ? (solved ? 'correct' : 'wrong') : ''} onClick={() => answerOption(optionIndex)}>{option}</button>)}</div>}{step.challenge.input === 'text' && <div className="tutorial-text-answer"><input value={text} onChange={(event) => { setText(event.target.value); setSolved(false) }} placeholder={step.challenge.placeholder} /><button disabled={!canSolveText} onClick={() => setSolved(true)}>Commit answer</button></div>}{selected !== null && !solved && <p className="tutorial-feedback negative">Not quite. Re-read the risk or execution objective and try again.</p>}{status && <p className="tutorial-feedback positive">{status}</p>}</div><div className="fund-tutorial-actions">{index > 0 && <button className="button button-ghost" onClick={() => { setIndex(index - 1); setSelected(null); setText(''); setSolved(false) }}>Back</button>}{index < steps.length - 1 ? <button className="button button-primary" disabled={!solved} onClick={next}>Next</button> : <button className="button button-primary" disabled={!solved} onClick={onStartPractice}>Start Learning session</button>}</div></article></section></main>
}
