interface Props { onClose: () => void }

export function MacroMethodologyModal({ onClose }: Props) {
  return <div className="modal-backdrop" role="presentation"><section className="modal-card methodology-modal" role="dialog" aria-modal="true" aria-labelledby="macro-methodology-title"><div className="modal-header"><div><p className="eyebrow">BUY-SIDE MODEL DOCUMENTATION</p><h2 id="macro-methodology-title">Buy-Side methodology</h2></div><button className="modal-close" type="button" onClick={onClose} aria-label="Close methodology">×</button></div><div className="methodology-content">
    <section><h3>Four buy-side modes</h3><p><strong>Global Macro Trader</strong> is continuous cross-asset trading. <strong>Strategic Portfolio Manager</strong> is the slower 30-day allocation mode. <strong>Long / Short Equity</strong> models single-name alpha, short borrow, beta hedging and catalysts. <strong>Long-Only Equity PM</strong> uses the same continuous equity engine but scores active decisions relative to a synthetic benchmark.</p></section>
    <section><h3>Portfolio accounting</h3><p>Positions are expressed as target NAV weights and converted into synthetic exposure units at execution prices. Long and short exposures mark to market continuously, cash is the residual after trades, and execution slippage is reflected immediately in NAV. Macro mode uses a 150% gross limit; long/short equity uses 200%; long-only is capped at 100% invested.</p></section>
    <section><h3>Continuous market engines</h3><p>Live modes update markets continuously using shared factors plus instrument-specific noise. Scheduled releases and company catalysts hit automatically while the user is deciding or executing. Learning mode reveals more of the simulated regime; harder modes require inference from prices, news and portfolio behaviour.</p></section>
    <section><h3>Equity hedge-fund mechanics</h3><p>The long/short engine separates market beta from single-name/factor risk, reports gross and net exposure, and allows ES futures to hedge portfolio beta. Single-name shorts require a synthetic prime-broker locate. Hard-to-borrow securities can have partial or rejected locates, higher annualised borrow rates and larger squeeze risk. Borrow costs accrue to short positions through the compressed session horizon.</p></section>
    <section><h3>Long-only asset management</h3><p>The long-only mandate prohibits short positions and compares the portfolio with a synthetic six-stock benchmark. Performance is therefore judged on active alpha, drawdown, concentration, turnover and execution rather than absolute return alone.</p></section>
    <section><h3>Execution routes</h3><p>Buy-side trades can cross the synthetic direct market, request firm two-way prices from three or five fictional dealers, or be worked over time. Dealer pricing varies with requested size and synthetic inventory axes. Worked orders execute in clips while the market keeps moving; patient execution lowers expected impact but leaves residual market risk.</p></section>
    <section><h3>Equity factors and catalysts</h3><p>Single-name returns combine market beta with growth, value, quality, rates and momentum factors plus idiosyncratic noise. Earnings, guidance, analyst revisions, strategic events and macro releases create additional dispersion. The securities are fictional and the loadings are training assumptions.</p></section>
    <section><h3>Thesis discipline</h3><p>Live journalling is optional so tactical hedges do not interrupt flow. Conviction positions can still be tagged by rationale, horizon, conviction and invalidation. Reviews compare the recorded view with the realised path.</p></section>
    <section><h3>Attribution and scoring</h3><p>Equity reviews separate asset P&amp;L, factor contributions, transaction costs, borrow costs and an estimated beta-versus-alpha decomposition. Long-only scoring emphasises benchmark-relative alpha; long/short scoring emphasises differentiated alpha after controlling broad beta and leverage.</p></section>
    <section><h3>Limitations</h3><p>The platform is educational. It abstracts precise prime-broker financing, margin, corporate actions, taxes, options convexity, locate recalls, real exchange routing and proprietary institutional risk systems. Dealer axes, borrow rates, factor loadings and catalyst outcomes are synthetic.</p></section>
  </div><div className="modal-actions methodology-actions"><span>DealerSim v2.5 · Dealer + Macro + Equity HF/AM</span><button className="button button-primary" type="button" onClick={onClose}>Close</button></div></section></div>
}
