import { useState } from 'react'

interface Props { onExit: () => void; onStartPractice: () => void }

export function MacroTutorial({ onExit, onStartPractice }: Props) {
  const [step, setStep] = useState(0)
  const [answer, setAnswer] = useState('')
  const [esWeight, setEsWeight] = useState(0)
  const [tyWeight, setTyWeight] = useState(0)
  const [invalidation, setInvalidation] = useState('')
  const [executionChoice, setExecutionChoice] = useState('')

  const inflationCorrect = answer === 'duration-down'
  const portfolioCorrect = esWeight <= -4 && tyWeight <= -4
  const executionCorrect = executionChoice === 'dealer-b'
  const canContinue = step === 0 || (step === 1 && inflationCorrect) || (step === 2 && portfolioCorrect) || (step === 3 && invalidation.trim().length >= 8) || (step === 4 && executionCorrect)

  return <main className="macro-tutorial-shell">
    <section className="macro-tutorial-card">
      <header><div><p className="eyebrow">INTERACTIVE BUY-SIDE TUTORIAL</p><h1>Global Macro · Step {step + 1} / 6</h1></div><button className="button button-ghost" type="button" onClick={onExit}>Exit</button></header>
      <div className="macro-tutorial-progress"><span style={{ width: `${((step + 1) / 6) * 100}%` }} /></div>
      {step === 0 && <div className="macro-tutorial-body"><h2>Your job is different from the dealer desk</h2><p>You are managing a $100m portfolio. You decide what to own, then choose how to execute: direct market or dealer RFQ. Your objective is to express views with disciplined position sizing, survive adverse paths and understand what actually drives your P&amp;L.</p><div className="macro-tutorial-metrics"><div><span>Gross limit</span><strong>150%</strong></div><div><span>Hard drawdown</span><strong>10%</strong></div><div><span>Single position</span><strong>25–35%</strong></div><div><span>Cash</span><strong>Residual NAV</strong></div></div></div>}
      {step === 1 && <div className="macro-tutorial-body"><h2>Interpret the surprise, not the headline</h2><div className="tutorial-release"><span>US CPI m/m</span><strong>0.5% actual vs 0.2% consensus</strong><small>A large upside inflation surprise.</small></div><p>Which immediate relationship is the cleanest starting point?</p><div className="tutorial-choice-grid"><button className={answer === 'duration-down' ? 'selected' : ''} onClick={() => setAnswer('duration-down')} type="button">Duration prices down; policy expectations more hawkish</button><button className={answer === 'duration-up' ? 'selected' : ''} onClick={() => setAnswer('duration-up')} type="button">Duration prices up because inflation is higher</button><button className={answer === 'nothing' ? 'selected' : ''} onClick={() => setAnswer('nothing')} type="button">No cross-asset implication</button></div>{answer && !inflationCorrect && <p className="negative">That is not the cleanest first-order read. Higher-than-expected inflation usually pressures duration through tighter expected policy / higher yields.</p>}</div>}
      {step === 2 && <div className="macro-tutorial-body"><h2>Express the view with portfolio weights</h2><p>For this tutorial only, build a small hawkish-inflation expression: short both ES and US duration. The objective is not to claim this is always optimal; it demonstrates how weights translate a macro view into portfolio risk.</p><label className="tutorial-slider"><span>ES target weight <strong>{esWeight}%</strong></span><input type="range" min="-10" max="10" value={esWeight} onChange={(event) => setEsWeight(Number(event.target.value))} /></label><label className="tutorial-slider"><span>TY target weight <strong>{tyWeight}%</strong></span><input type="range" min="-10" max="10" value={tyWeight} onChange={(event) => setTyWeight(Number(event.target.value))} /></label><div className="tutorial-exposure-readout"><span>Gross <b>{Math.abs(esWeight) + Math.abs(tyWeight)}%</b></span><span>Net <b>{esWeight + tyWeight}%</b></span><span>Direction <b>{portfolioCorrect ? 'Hawkish inflation' : 'Not yet expressed'}</b></span></div></div>}
      {step === 3 && <div className="macro-tutorial-body"><h2>Every position needs an invalidation</h2><p>A thesis is incomplete if you only state what could make money. Write the condition that would make you reassess the trade.</p><label className="tutorial-textarea"><span>Example: “Inflation data normalises and the hawkish rates repricing reverses.”</span><textarea value={invalidation} onChange={(event) => setInvalidation(event.target.value)} placeholder="What would make you reassess?" /></label></div>}
      {step === 4 && <div className="macro-tutorial-body"><h2>Portfolio idea and execution are separate decisions</h2><p>You want to BUY a $10m block. Direct market execution is available at 5400.75 with estimated implementation cost of $7,000. Three dealers return firm quotes. Which is the best executable offer?</p><div className="tutorial-choice-grid"><button className={executionChoice === 'dealer-a' ? 'selected' : ''} onClick={() => setExecutionChoice('dealer-a')} type="button">Northbank · 5400.45 / 5400.70 · Neutral</button><button className={executionChoice === 'dealer-b' ? 'selected' : ''} onClick={() => setExecutionChoice('dealer-b')} type="button">Mercator · 5400.36 / 5400.58 · Strong axe to sell</button><button className={executionChoice === 'dealer-c' ? 'selected' : ''} onClick={() => setExecutionChoice('dealer-c')} type="button">Albion · 5400.55 / 5400.88 · Bid wanted</button></div>{executionChoice && !executionCorrect && <p className="negative">For a buy order, compare the dealers' offers. The sell axe is useful because your purchase helps that dealer reduce inventory, so they can quote more aggressively.</p>}{executionCorrect && <p className="positive">Correct. You would buy at Mercator's 5400.58, better than the direct-market benchmark. An axe is useful colour, but in the live simulator it will not always produce the best quote.</p>}</div>}
      {step === 5 && <div className="macro-tutorial-body"><h2>Then manage the path, not just the destination</h2><div className="macro-tutorial-checklist"><div><b>1</b><span>Compare actual data with consensus.</span></div><div><b>2</b><span>Translate the surprise into factors and cross-asset implications.</span></div><div><b>3</b><span>Size the position in NAV terms and inspect factor concentration.</span></div><div><b>4</b><span>Choose direct-market or dealer RFQ execution based on actual executable cost.</span></div><div><b>5</b><span>Update or cut the position when the thesis is invalidated.</span></div><div><b>6</b><span>Review whether P&amp;L came from thesis, beta, timing, execution or idiosyncratic noise.</span></div></div></div>}
      <footer>{step > 0 && <button type="button" className="button button-ghost" onClick={() => setStep((value) => Math.max(0, value - 1))}>Back</button>}<div /><button type="button" className="button button-primary" disabled={step < 5 && !canContinue} onClick={() => step === 5 ? onStartPractice() : setStep((value) => value + 1)}>{step === 5 ? 'Start guided macro mandate' : 'Continue'}</button></footer>
    </section>
  </main>
}
